# Setup
title:               Nicky Marino
tagline:             ''
description:         'Nicky Marino'
url:                 https://nickymarino.com
baseurl:             ''
paginate:            3
paginate-path:       'page:num'
plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# About/contact
author:
  name:              Nicky Marino
  url:               https://nickymarino.com
  github:            https://github.com/nickymarino
  email:             nicky.s.marino@gmail.com
  linkedin:          https://www.linkedin.com/in/nicky-marino-9a204bbb/
  twitter:           https://twitter.com/_NickyMarino

# Permalinks
permalink:           pretty

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

twitter_feed:        https://twitter.com/NickyMarino_com
source_url:          https://github.com/nickymarino/nickymarino.github.io
